import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "../components/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
    <body className={`${inter.className} min-h-screen flex flex-col`}>
        <NavigationBar />
        <div className="flex flex-1 justify-center items-center w-full">
          {children}
        </div>
      </body>
    </html>
    </>
  );
}
